### ISSUE TITLE
can you make my hack for me?

### ISSUE THREAD

**Issue by Fatih120** [RIAEvangelist/is-my-node-supply-chain-secure#1]
feuniverse sucks so i think you should make my hack for me.

i want ephriam to have max stats and start in the amin party because he is so cool. also put me in and let me have s supports with eirika ( u need into install Skills sytem because its really cool you need the one skkill called camamaerie.. i forgot), also WTF no seth please he's so broken!!! 😠 i need 2 coninu later bc im all out of ideas... o yeah b sure to give eirika silver sword :D ty

**Comment by RIAEvangelist** [comment]
I'm sorry I can't help with this.
