### ISSUE TITLE
-

### ISSUE THREAD

**Issue by TheMikeyRoss** [RIAEvangelist/is-my-node-supply-chain-secure#2]

**Comment by Krutoy-4el** [comment]
*a hero 🤭

**Comment by TheOtterlord** [comment]
> *a hero 🤭

@Krutoy-4el not sure how wiping the computers of fellow developers can be considered "heroic". And even if you somehow believe that Russians and Belarusians who have no control over the situation deserve this, take note that this has also damaged attempts to document human rights violations and war crimes commited by these countries leaders<sup>[1](https://snippet.host/kvcb)</sup> <sup>[2](https://github.com/IdealismIncinerator/node-ipc/blob/master/README.md#a-major-victim)</sup>. In addition, he has attempted to cover up his crimes, lie about the impact, and censor people who tried to warn others of the malware and it's impact<sup>[3](https://github.com/IdealismIncinerator/node-ipc/blob/master/README.md#more-cover-ups)</sup>.

**Comment by TheOtterlord** [comment]
[full story for those interested in why people no longer trust this guy](https://github.com/IdealismIncinerator/node-ipc/blob/master/README.md)
